events { worker_connections 1024; }
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name cloud.local 192.168.1.2;

        location /storage-console/ {
            proxy_pass http://minio:9001/;
            proxy_set_header Host $host;
        }
        location /storage/ {
            proxy_pass http://minio:9000/;
            proxy_set_header Host $host;
        }
        location /monitor/ {
            proxy_pass http://grafana:3000/;
            proxy_set_header Host $host;
        }
        location /metrics/ {
            proxy_pass http://prometheus:9090/;
            proxy_set_header Host $host;
        }
        location /api/ {
            proxy_pass http://iaas-api:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /assets/js/ {
            root /usr/share/nginx/html;
            types { application/javascript js mjs; }
            default_type application/javascript;
            try_files $uri =404;
        }
        location /assets/css/ {
            root /usr/share/nginx/html;
            types { text/css css; }
            default_type text/css;
            try_files $uri =404;
        }
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ =404;
        }
    }
}
